### ISSUE TITLE
EDDBApi factions request 504ing when using homesystemname argument

### ISSUE THREAD

**Issue by EricJFisher** [SayakMukhopadhyay/eddbapi#19]
When calling the faction's request on the EDDBApi if you include only the `homesystemname` argument it 504 times out. (This started on 04/01/2021 EST it worked fine before that)

Example: https://eddbapi.kodeblox.com/api/v4/factions?homesystemname=heheng

**Comment by SayakMukhopadhyay** [comment]
Thanks for the report. This is now fixed by f8d01a2f1867c7116e0531f0ce446702c5cc290c and has been deployed. Please check and reopen this issue if necessary.
